androidAppId: com.CMR.emesalud_hmc
iosAppId: com.CMR.emesalud.hmc

name: Honduras Medical Center
nameShort: HMC
webpage: https://hmc.com.hn/
ip: ris.hmc.hn
usesHttps: true

contact_telephone: "5555555555"
contact_email: contacto@cmr3.com
contact_hours: De lunes a viernes de 7 a 20 hrs
contact_address: Revolucion 756

baseUrl: /HisWebServicios/Portal/ServicioPortal.svc
baseUrlPACS: /visorhtml5/WcfServiceIconos/Service1.svc
baseVisorPACS: /WebUltimateGL/App/Vistas/desktop.html

iconBackgroundColor: "#bee4ed"

color_primary: 0xff09488F
color_accent: 0xffE30D18
color_primaryDark: 0xff5393b3
color_accentDark: 0xffe45443
color_primaryLight: 0xffbee4ed
color_accentLight: 0xfff7b5a2
color_loadingGrey: 0xffffffff

debugMode: true
hasImaging: true
hasLaboratory: false
hasPathology: false
hasDirectory: false
canMakeAppointmets: false
hasBanner: true
hasRecord: false
showAppointments: false